/**
 * 榜单列定义 · 基础面 / 估值 / 行业列（默认可见）
 *
 * 从 `lib/rankingColumns.ts` 拆出（铁律 9）。列顺序 = 数组顺序，
 * 三组按 base → quote → technical 拼接，与拆分前完全一致。
 */
import type { RankingColumn } from './types'

export const BASE_COLUMNS: RankingColumn[] = [
  {
    key: 'score',
    label: '综合评分',
    align: 'right',
    width: 92,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '综合评分（候选观察池依据）',
      what: '把「估值 / 质量 / 位置 / 趋势」四个维度各自打 0~100 分后加权成的总分。每一分都能溯源：鼠标移到分数上可以看到四个维度分别得了多少、各自的理由。',
      how: '分数越高说明这四个维度越没有明显短板，越值得你逐个去看。默认 ≥ 70 分归入「候选观察池」—— 阈值可以在上方拖。',
      warn: '这不是买入信号。本项目的复盘结论是：规则化策略在收益上打不过买入持有，真实价值在回撤控制。这个分数只做一件事 —— 把 500 多只缩到你愿意逐个看的一小撮。缺数据的维度不计入总分（权重重新归一），此类标的会标「数据不全」，分数仅供参考。',
    },
  },
  {
    key: 'signals',
    label: '关注信号',
    align: 'left',
    width: 172,
    defaultOn: true,
    tip: {
      title: '关注信号（选股中心）',
      what: '由确定性规则生成的机会 / 风险提示：红色 = 机会（如「同行业便宜 + 盈利强」），橙色 = 风险（如「短期超买」「股息陷阱嫌疑」）。每个信号必须同时满足多个独立条件才会亮灯，悬停可以看到触发时的具体数值。',
      how: '把它当作「为什么这只出现在眼前」的一行摘要：有红色信号 → 值得点开公司档案细看；有橙色信号 → 看的时候多留个心眼。点击信号可以在下方筛选出同类标的。',
      warn: '信号是筛选辅助，不是买入信号。每个信号都有明确的失效场景（悬停可见）—— 例如强趋势中「超买」可以长期钝化，深度回撤可能是基本面真的坏了。',
    },
  },
  {
    key: 'symbol',
    label: '代码 / 名称',
    align: 'left',
    width: 116,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '代码 / 名称',
      what: '美股代码（如 AAPL）与公司名。中文名来自腾讯行情，点代码或名称可打开公司档案。',
      how: '点列头按字母排序，便于在一长串里定位某只股票。',
    },
  },
  {
    key: 'price',
    label: '现价',
    align: 'right',
    width: 64,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '现价',
      what: '最新成交价（美元）。数据来自行情源，可能有十几分钟延迟。',
      how: '与「距 52 周高」一起看，能快速判断这只股票处在什么位置。',
    },
  },
  {
    key: 'change_pct',
    label: '涨跌幅',
    align: 'right',
    width: 70,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '涨跌幅',
      what: '相对上一交易日收盘价的涨跌百分比。',
      how: '红色为上涨、绿色为下跌（A 股配色习惯，可在设置里切换）。按降序看就是当日强势榜。',
      warn: '单日涨跌幅噪音很大，不适合作为选股依据；它衡量的是情绪，不是价值。',
    },
  },
  {
    key: 'amount',
    label: '成交额',
    align: 'right',
    width: 64,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '成交额',
      what: '当日成交金额 = 现价 × 成交量。',
      how: '衡量流动性。成交额太小的标的买卖价差大、冲击成本高，不适合重仓。',
    },
  },
  {
    key: 'market_cap',
    label: '总市值',
    align: 'right',
    width: 66,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '总市值',
      what: '总股本 × 现价，代表市场对这家公司的整体定价。',
      how: '大盘股（> 1000 亿美元）流动性好、波动小；小盘股弹性大但风险高。',
      warn: '注意与「流通市值」区分：存在大量未流通股份的公司，两者差异可能很大。',
    },
  },
  {
    key: 'pe_ttm',
    label: '市盈率 PE',
    align: 'right',
    width: 96,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '市盈率 PE（TTM）',
      what: '现价 ÷ 最近 12 个月每股收益。通俗说就是「按当前盈利能力，多少年回本」。',
      how: '越低越便宜，但必须和同行业比。参考：< 15 偏低、15~25 常见、> 40 偏贵（高成长科技股例外）。后面的色条是它在同行业里的分位：越靠左越便宜，越靠右越贵。',
      warn: '亏损公司 PE 没有意义（显示「亏损」）；一次性损益会让 PE 严重失真（卖资产、大额减值都会扭曲）；PE > 200 已单独标记为「异常」，不参与估值排序。周期股在盈利高点时 PE 反而最低，是典型陷阱。',
    },
  },
  {
    key: 'pb',
    label: '市净率 PB',
    align: 'right',
    width: 56,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '市净率 PB',
      what: '现价 ÷ 每股净资产，衡量股价相对公司账面价值贵多少。',
      how: '最适合银行、保险、地产、公用事业等重资产行业：< 1 表示股价跌破净资产。轻资产公司（科技、消费品牌）PB 天然很高，不能拿来横向比。',
      warn: '高 PB 不等于高估 —— 关键看 ROE：只要 ROE 足够高，高 PB 是合理的（PB ≈ PE × ROE）。净资产为负时不显示。',
    },
  },
  {
    key: 'roe',
    label: 'ROE',
    align: 'right',
    width: 60,
    sortable: true,
    defaultOn: true,
    tip: {
      title: 'ROE 净资产收益率',
      what: '公司用股东每 1 元净资产赚回多少利润。本页由 PB ÷ PE 推算（TTM 口径）。',
      how: '这是「质量」指标，与贵不贵无关。长期 > 15% 通常说明有竞争优势（护城河），< 8% 偏弱。最经典的组合筛选是「低 PE + 高 ROE」：又便宜又能赚钱。',
      warn: '高负债会推高 ROE（靠借钱而不是靠盈利能力），所以高 ROE 要结合负债水平看。本页数值由 PB ÷ PE 推算（TTM），与财报披露的加权 ROE 可能有差异；超过 300% 的一律不显示 —— 那通常意味着净资产趋近于 0（大额回购或累计亏损），数字已失去意义。',
    },
  },
  {
    key: 'div_yield',
    label: '股息率',
    align: 'right',
    width: 62,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '股息率',
      what: '每股年度现金分红 ÷ 现价，即只靠分红每年能拿到的现金回报率。',
      how: '拿它和无风险利率（美债收益率）比：明显更高才有吸引力。一般 > 3% 算高股息，适合追求现金流的稳健配置。',
      warn: '异常高的股息率（如 > 8%）往往是股价大跌或一次性特别分红造成的，很可能是「股息陷阱」—— 分红不可持续。不分红的公司显示「—」，这只是公司选择把利润再投资，不代表不好。',
    },
  },
  {
    key: 'pct_from_high',
    label: '距 52 周高',
    align: 'right',
    width: 74,
    sortable: true,
    defaultOn: true,
    tip: {
      title: '距 52 周高',
      what: '（现价 − 52 周最高价）÷ 52 周最高价，单位 %。',
      how: '越接近 0% 越强势（接近年内新高，趋势策略偏好）；-30% 以下属于深度回撤（超跌反弹策略偏好）。它衡量「位置」，不衡量「贵贱」。',
      warn: '强势 ≠ 便宜：接近新高时 PE 往往也在高位。反之跌得多的股票也可能是基本面真的变差了。',
    },
  },
  {
    key: 'sector',
    label: '行业',
    align: 'left',
    width: 132,
    defaultOn: true,
    tip: {
      title: '行业（GICS 一级）',
      what: '公司所属行业分类（GICS 口径），来自 S&P 500 / NASDAQ 100 / S&P 400 成分快照。',
      how: '估值指标必须在行业内比较：银行 PE 14 和软件 PE 40 可能都算合理。上方的「行业」下拉可以只看某一个行业。',
    },
  },
]
